### ISSUE TITLE
Tool does not detect game process

### ISSUE THREAD

**Issue by von-de** [shiversoftdev/t7patch#5]
When the tools is opened, and Black Ops 3 is opened afterwards, the tool never hooks onto Black Ops 3 for me and just says "No game process found". I am tabbed into the game and have not pressed any keys yet.

Process name: BlackOps3.exe
PID: 16132

If you need anything else to diagnose the cause of this issue, feel free to ask me.

**Comment by KarlHder2te** [comment]
**Addendum:** I tested the following cases:
- Attempt after PC restart
- Having both BO3 and the Patch de-escalated by using a registry shell edit on the patch EXE
- Having both BO3 and the Patch UAC escalated
None of these attempts have yielded any success in getting the Patch to detect the BO3 task.

**Comment by shiversoftdev** [comment]
Since it seems like you are Windows tuning literate, I will advise you to try the patch on a stock configuration that does not adjust token privileges of any type. What has likely happened is a de-escalation of privs that caused my openprocess call to fail with access denied or something along those lines. 

The injector will say the process is not found if the injection fails, which can often happen as a result of wonky privileges or antivirus interception. You may want to review security events in the event viewer to see if anything is firing, or turn on audit logs for security events temporarily. Otherwise, I can ship a new version of the patch that will log failures to inject upon a special command line execution of the process and then you can tell me what it outputs.

**Comment by KarlHder2te** [comment]
Thank you for the reply.

Unfortunately, I am unable to try the patch on a stock configuration. Though, I had not messed too much with token privileges myself so far.
I’ve attached a log of security logs with audit security events enabled, however, I’ve also found an odd occurrence today:
The first time I’ve started Black Ops 3 today resulted in a successful hook, however, shortly after, the game crashed before I was able to interact with the UI. All related security events related to that occurrence are logged in “evbo32.evtx” (if I recall correctly).
All failed attempts of a hook are attached in “evbo31.evtx”, however, I’d like to note that today every failure had also resulted in Black Ops 3 first locking up with a warning sound, then completely crashing to desktop. This has not occurred before.
What does irritate me is that something seems to be invoking NT AUTHORITY irregularly in these cases; I don’t think that should happen and I’m not sure why it would do that. I’m not sure why it would be needed either for a Black Ops 3 patch, unless something needs to be patched at a low level.

I’d appreciate it if you would ship a version that logs failures specific to this event. Please let me know where log files would be created so I can get them to you.

Cheers!

**Comment by shiversoftdev** [comment]
Hello, a new file "errors.txt" should now be written. Please run 1.06 and let me know what happens. Thanks!

**Comment by shiversoftdev** [comment]
Update: Someone with this issue reported it and gave logs. It appears RPC is timing out on some calls, which may have to do with QUAPC2 behavior on some machines. Will need to look into this further. May consider fallback to thread hijacking if necessary.

**Comment by 12Milkmen** [comment]
I'm also having this issue I let it through my anti virus but still nothing and here is the error log I got

[errors.txt](https://github.com/shiversoftdev/t7patch/files/10009702/errors.txt)

**Comment by von-de** [comment]
@shiversoftdev Apologies for the delay, I had been busy.
I've done some more testing on my system now (three tests in total today). The first two tests did not work; every time the tool displayed that it protected the game process the game completely froze and became unresponsive; despite that, Windows did not declare it as "Not responding". 
The third launch worked without flaws; the game was successfully protected and name changes properly applied on menu switches. On that same launch I then proceeded to play a game of Zombies up until Round 5, after which I ended the zombies game and closed Black Ops 3 through the main menu Exit option without any issues whatsoever. The tool also fixed any "slow menu" issues for me that I usually had when playing vanilla.

[Error File 1](https://pastebin.com/WpxsVrnG)
[Error File 2](https://pastebin.com/2mWawnSQ)
[Error File 3](https://pastebin.com/vvsVD7u0)

Note that the exit errors in the first file are likely because I task-killed the game after it stopped responding to inputs (ALT+F4 did not work). I made a mistake with the second file and submitted it to Pastebin before the game was closed; identical exit errors were showing up after I task-killed the game after the second failed launch.

**Comment by shiversoftdev** [comment]
Hello @von-de, 

These errors are seemingly out of my control and are not related to the application. Something with your setup has caused RPM/WPM syscalls to fail, either due to architecture boundaries (something is running 32bit when it shouldn't be, WOW64 emulation messing up, etc) or due to antivirus/kernel interference.

As this is clearly not an application issue, I will be closing this. Thank you for the error logs, and I wish you the best of luck with getting your system configuration sorted out.
